version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8100:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbOptions__ConnectionString=mongodb://catalogdb:27017 
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=basketdb:6379
    depends_on:
      - basketdb
    ports:
      - "8001:8080"
  
  pgadmin:
    container_name: pgadmin
    restart: always
    ports:
      - "8101:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@bies.com
      - PGADMIN_DEFAULT_PASSWORD=Admin123!
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123!
      - POSTGRES_DB=discount
    volumes:
      - discount_data:/var/lib/postgresql/data
  
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__PostgreSqlConnectionString=Host=discountdb;Port=5432;Database=discount;Username=postgres;Password=Admin123!
    depends_on:
      - discountdb
    ports:
      - "8002:8080"
