version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8100:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalog_data:/data/db

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbOptions__ConnectionString=mongodb://catalogdb:27017 
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=basketdb:6379
      - ConnectionStrings__DiscountGrpc=http://discount.grpc:8080
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:8080"
  
  pgadmin:
    container_name: pgadmin
    restart: always
    ports:
      - "8101:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@bies.com
      - PGADMIN_DEFAULT_PASSWORD=Admin123!
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123!
      - POSTGRES_DB=discount
    volumes:
      - discount_data:/var/lib/postgresql/data
  
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__PostgreSqlConnectionString=Host=discountdb;Port=5432;Database=discount;Username=postgres;Password=Admin123!
    depends_on:
      - discountdb
    ports:
      - "8002:8080"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__PostgreSqlConnectionString=Host=discountdb;Port=5432;Database=discount;Username=postgres;Password=Admin123!
    depends_on:
        - discountdb
    ports:
      - "8080" # We dont need to expose grpc port to outside world because it is only used by internal services. But for debugging you can always expose it to 8003

  orderingdb:
    container_name: orderingdb
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123!
      - MSSQL_PID=Developer
    volumes:
        - order_data:/var/opt/mssql
      # - order_data/data:/var/opt/mssql/data
      # - order_data/log:/var/opt/mssql/log
      # - order_data/secrets:/var/opt/mssql/secrets

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OrderingConnectionString=Data Source=orderingdb,1433;Initial Catalog=OrderingDb;User ID=sa;Password=Admin123!;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - orderingdb
      - rabbitmq
    ports:
      - "8004:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

  rabbitmq:
    container_name: rabbitmq
    restart: always
    hostname: ms-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - discount.grpc
      - ordering.api
    ports:
      - "8010:8080"


  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__BasketUrl=http://basket.api:8080
      - ApiSettings__CatalogUrl=http://catalog.api:8080
      - ApiSettings__OrderingUrl=http://ordering.api:8080
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "8005:8080"


  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_HTTP_PORTS=8080
      #- ASPNETCORE_HTTPS_PORTS=8081
      - ApiSettings__GatewayAddress=http://ocelotapigw:8080
    depends_on:
      - ocelotapigw
      - catalog.api 
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8006:8080"
      #- "8081" # For https
    #volumes:
      #- ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro # For https
